# Oxidize Recipe - Phase 2 MVP
# Build embeddings and projections from unified eventlog

version: 1
embedding_model: e5-base-v2

projections:
  # Semantic projection - observations from same session are similar
  semantic:
    layers: [768, 1024, 256]
    epochs: 10
    batch_size: 32
