//! Internal implementation for Gemini adapter (stub)

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::environment::Environment;

/// Path constants for Gemini adapter
const ADAPTER_DIR: &str = ".gemini";
const CONTEXT_FILE: &str = "GEMINI.md";

/// Initialize Gemini project structure
pub fn init_project(project_path: &Path, project_name: &str, environment: &Environment) -> Result<()> {
    // Create .gemini directory
    let gemini_path = project_path.join(ADAPTER_DIR);
    fs::create_dir_all(&gemini_path)?;

    // Generate initial context
    let content = generate_minimal_context(project_name, environment);
    fs::write(gemini_path.join(CONTEXT_FILE), content)?;

    Ok(())
}

// Removed pattern-based context generation
// TODO: Implement real pattern extraction

/// Get context file path
pub fn get_context_file_path(project_path: &Path) -> PathBuf {
    project_path.join(ADAPTER_DIR).join(CONTEXT_FILE)
}

/// Generate minimal context for Gemini
fn generate_minimal_context(project_name: &str, environment: &Environment) -> String {
    let mut content = String::new();

    // Header
    content.push_str(&format!("# {project_name} - Gemini Context\n\n"));
    content.push_str("Project context for Gemini AI.\n");
    content.push_str("See root `GEMINI.md` or `README.md` for project instructions.\n\n");

    // Environment
    content.push_str("## Environment\n\n");
    content.push_str(&format!(
        "- **Platform**: {} ({})\n",
        environment.os, environment.arch
    ));
    content.push_str(&format!("- **Directory**: {}\n", environment.current_dir));

    // Available tools
    let tools = ["cargo", "git", "docker", "python"];
    let available: Vec<_> = tools
        .iter()
        .filter_map(|&tool| {
            environment
                .tools
                .get(tool)
                .filter(|info| info.available)
                .map(|_| tool)
        })
        .collect();

    if !available.is_empty() {
        content.push_str(&format!("- **Tools**: {}\n", available.join(", ")));
    }
    content.push('\n');

    // TODO: Implement real pattern discovery
    content.push_str("## Patterns\n\n");
    content.push_str("See files in `layer/` directory for patterns and documentation.\n\n");

    // Footer
    content.push_str(&format!(
        "---\n*Generated by Patina v{}*\n",
        env!("CARGO_PKG_VERSION")
    ));

    content
}
