//! Internal implementation for OpenCode adapter

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::adapters::templates;
use crate::environment::Environment;

/// Path constants for OpenCode adapter
const ADAPTER_DIR: &str = ".opencode";
const CONTEXT_FILE: &str = "AGENTS.md";

/// Initialize OpenCode project structure
pub fn init_project(
    project_path: &Path,
    project_name: &str,
    environment: &Environment,
) -> Result<()> {
    // Copy templates from central location (~/.patina/adapters/opencode/templates/)
    templates::copy_to_project("opencode", project_path)?;

    // Generate context file in .opencode/
    ensure_context_file(project_path, project_name, environment)?;

    Ok(())
}

/// Get context file path
pub fn get_context_file_path(project_path: &Path) -> PathBuf {
    project_path.join(ADAPTER_DIR).join(CONTEXT_FILE)
}

pub fn ensure_context_file(
    project_path: &Path,
    project_name: &str,
    environment: &Environment,
) -> Result<PathBuf> {
    let opencode_path = project_path.join(ADAPTER_DIR);
    fs::create_dir_all(&opencode_path)?;
    let context_path = opencode_path.join(CONTEXT_FILE);
    if !context_path.exists() {
        let content = generate_minimal_context(project_name, environment);
        fs::write(&context_path, content)?;
    }
    Ok(context_path)
}

/// Generate minimal context for OpenCode
fn generate_minimal_context(project_name: &str, environment: &Environment) -> String {
    let mut content = String::new();

    // Header
    content.push_str(&format!("# {project_name} - AI Agent Context\n\n"));
    content.push_str("Project context for OpenCode and AI agents.\n");
    content.push_str("See root `AGENTS.md` or `README.md` for project instructions.\n\n");

    // Environment
    content.push_str("## Environment\n\n");
    content.push_str(&format!(
        "- **Platform**: {} ({})\n",
        environment.os, environment.arch
    ));
    content.push_str(&format!("- **Directory**: {}\n", environment.current_dir));

    // Available tools
    let tools = ["cargo", "git", "docker", "python"];
    let available: Vec<_> = tools
        .iter()
        .filter_map(|&tool| {
            environment
                .tools
                .get(tool)
                .filter(|info| info.available)
                .map(|_| tool)
        })
        .collect();

    if !available.is_empty() {
        content.push_str(&format!("- **Tools**: {}\n", available.join(", ")));
    }
    content.push('\n');

    // Patterns
    content.push_str("## Patterns\n\n");
    content.push_str("See files in `layer/` directory for patterns and documentation.\n\n");

    // MCP Tools
    content.push_str("## MCP Tools (Use These First)\n\n");
    content.push_str("Patina's authoritative interface surface is MCP, not shell-output scraping.\n\n");
    content.push_str("**Core discovery**\n");
    content.push_str("- `context` - architecture, beliefs, and project patterns before non-trivial changes\n");
    content.push_str("- `scry` - codebase knowledge search when you need implementation context\n");
    content.push_str("- `assay` - exact structural/code inventory questions\n\n");
    content.push_str("**Session workflow**\n");
    content.push_str("- `session.start` - start a new Patina session and get the durable artifact path\n");
    content.push_str("- `session.update` - append a git-aware update to the current live session\n");
    content.push_str("- `session.end` - archive the live session and update the last-session pointer\n");
    content.push_str("- `session.list` - inspect active/stale/recent sessions if selection is ambiguous\n\n");
    content.push_str("**Spec workflow**\n");
    content.push_str("- `spec.next` - decide what should be worked next\n");
    content.push_str("- `spec.list` / `spec.ready` / `spec.blocked` - navigate the queue\n");
    content.push_str("- `spec.show` - load spec context before coding\n");
    content.push_str("- `spec.check` - verify exit criteria truthfully\n");
    content.push_str("- `spec.create` / `spec.set` - mutate spec state only when the workflow actually needs it\n\n");
    content.push_str("Prefer MCP for session/spec actions. Use CLI `--json` only when MCP is unavailable.\n\n");

    // Footer
    content.push_str(&format!(
        "---\n*Generated by Patina v{} | Frontend: OpenCode*\n",
        env!("CARGO_PKG_VERSION")
    ));

    content
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_context_surfaces_session_and_spec_mcp_tools() {
        let environment = Environment {
            os: "macos".to_string(),
            arch: "arm64".to_string(),
            home_dir: "/tmp".to_string(),
            current_dir: "/tmp/project".to_string(),
            tools: Default::default(),
            languages: Default::default(),
            env_vars: Default::default(),
        };

        let content = generate_minimal_context("patina", &environment);
        assert!(content.contains("session.start"));
        assert!(content.contains("session.update"));
        assert!(content.contains("session.end"));
        assert!(content.contains("spec.next"));
        assert!(content.contains("spec.check"));
    }
}
