[package]
name = "{{ package_name }}"
version = "0.1.0"
edition = "2021"
description = "{{ description }}"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
patina-sdk = "0.22.0"
wit-bindgen = "0.41.0"

[package.metadata.component]
package = "patina:{{ child_name }}"

[package.metadata.component.target]
path = "wit"
world = "{{ child_name }}"
