[package]
name = "patina-ai-child-schema-enforcer"
version = "0.1.0"
edition = "2021"
description = "Validate extracted records against schema"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.41.0"
patina-sdk = { path = "../../sdk/patina-sdk" }

[package.metadata.component]
package = "patina:schema-enforcer"

[package.metadata.component.target]
path = "wit"
world = "schema-enforcer"
