pub mod adapter;
pub mod ask;
pub mod audit;
pub mod belief;
pub mod build;
pub mod doctor;
pub mod embeddings;
pub mod eval;
pub mod init;
pub mod launch;
pub mod oxidize;
pub mod persona;
pub mod query;
pub mod rebuild;
pub mod repo;
pub mod scrape;
pub mod scry;
pub mod serve;
pub mod test;
pub mod upgrade;
pub mod version;
pub mod yolo;

#[cfg(feature = "dev")]
pub mod dev;
