[package]
name = "patina-ai-adapter-df-pando"
version = "0.1.0"
edition = "2021"
description = "Pando dedup transform adapter"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.41.0"

[package.metadata.component]
package = "patina:df-pando"

[package.metadata.component.target]
path = "wit"
world = "df-pando"
