[package]
name = "patina-ai-adapter-rw-pando"
version = "0.1.0"
edition = "2021"
description = "Pando write adapter"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.41.0"

[package.metadata.component]
package = "patina:rw-pando"

[package.metadata.component.target]
path = "wit"
world = "rw-pando"
