[child]
name = "file-system-monitor"
kind = "child"
role = "app"

[needs]
toys = ["logging", "measure", "filesystem"]

[needs.scopes.filesystem]
path = "/tmp"

[needs.metrics]
files_discovered = { type = "counter", labels = ["source_folder"] }
