[package]
name = "patina-ai-child-parquet-writer"
version = "0.1.0"
edition = "2021"
description = "Write ready records to parquet batches"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.41.0"
patina-sdk = { path = "../../sdk/patina-sdk" }
chrono = "0.4"
arrow-array = "55"
arrow-schema = "55"
parquet = { version = "55", default-features = false, features = ["arrow"] }

[package.metadata.component]
package = "patina:parquet-writer"

[package.metadata.component.target]
path = "wit"
world = "parquet-writer"
