package patina:dedup-filter@0.1.0;

world dedup-filter {
    import wasi:logging/logging@0.1.0;
    import wasi:keyvalue/store@0.2.0;
    import patina:measure/measure@0.1.0;
    export patina:records/transform@0.1.0;
}
