package patina:host@0.1.0;

interface ingress {
    record granted-source {
        name: string,
        endpoint: string,
    }

    list-granted-sources: func() -> list<granted-source>;
    fetch: func(source-name: string) -> result<string, string>;
}
